image: docker:20
services:
  - docker:dind
build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/rcastellotti/signs.rcastellotti.dev/frontend:latest .
    - docker push registry.gitlab.com/rcastellotti/signs.rcastellotti.dev/frontend:latest
    - docker build -t registry.gitlab.com/rcastellotti/signs.rcastellotti.dev/backend:latest ./backend
    - docker push registry.gitlab.com/rcastellotti/signs.rcastellotti.dev/backend/latest
  only:
    - main
